modLoader="javafml"
loaderVersion="[39,)"
license="ARR"
[[mods]]
modId="species"
version="1.19.2-1.0.0"
displayName="Species"
logoFile= "species.png"
authors="Ninni,Noon, Bornulhu, FloofHip, GLaDOS edition"
description='''
A mod that adds fictional mobs to the game, with cool and unique functions

Contributors:
- bunten
- Orcinus

'''
[[dependencies.species]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.species]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
